name: Lint

on: [push]

jobs:
  lint:
    name: Check coding style
    runs-on: ubuntu-latest
    steps:
      # clone repo and check out
      - uses: actions/checkout@v3

      - name: Check that all Python code is linted with black and typehints are checked with pyright
        run: pip install black pyright && black . --check && pyright
