name: Lint

on: [push]

jobs:
  lint:
    name: Check coding style
    runs-on: ubuntu-latest
    steps:
      # clone repo and check out
      - uses: actions/checkout@v3

      - name: Check that all Python code is linted with black
        run: pip install black==25.1.0 && black . --check

  typehints:
    name: Check type hints
    runs-on: ubuntu-latest
    steps:
      # clone repo and check out
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Check that all Python code has correct type hints with pyright
        run: pyright .
